platform :ios, '9.0'

target 'TrumpBot' do

  use_frameworks!

  # Pods for TrumpBot
  
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
